### ISSUE TITLE
Return usernames too

### ISSUE THREAD

**Issue by itscarlosrufo** [duiker101/twitter-interaction-circles#1]
Use case: https://twitter.com/swcarlosrj/status/1273887551099752448
I would like to have the @ usernames of everyone somehow, people could copy&paste on a tweet and they'd be able to follow their connections!

Congrats on such great work 🎊

**Comment by duiker101** [comment]
Fixed in https://github.com/duiker101/twitter-interaction-circles/commit/174668805ceef3afd71e56c7762b7e176976b527

You can now run 

```sh
yarn build --text
```

and the output with all the usernames will be in a users.txt file in the root of the project. Ready for use! 🥳

**Comment by itscarlosrufo** [comment]
Very much appreciated @duiker101 🎊 Have a fantastic weekend
