### ISSUE TITLE
No picture is being generated

### ISSUE THREAD

**Issue by BolverBlitz** [duiker101/twitter-interaction-circles#2]
Fetching user GodOfOwls
Fetching Timeline page 1
Fetching Timeline page 2
Fetching Timeline page 3
Fetching Timeline page 4
Fetching Liked page 1
Fetching Liked page 2
Fetching Liked page 3
Fetching avatars 49
Done in 6.38s.

Other usernames work just fine, but here it does not work.

**Comment by chk1** [comment]
I had the same issue. When there are deleted user accounts, `users[i].avatar` is `undefined` and the script silently fails (like in your example).

https://github.com/duiker101/twitter-interaction-circles/blob/174668805ceef3afd71e56c7762b7e176976b527/src/image.js#L54

Try surrounding that line with an if..else, maybe like so:

```
console.log(users[i].avatar);
if(users[i].avatar){
	const img = await loadImage(users[i].avatar);
	ctx.drawImage(
		img,
		centerX - radius,
		centerY - radius,
		radius * 2,
		radius * 2
	);
} else {
	console.log("Missing avatar image for");
	console.log(users[i]);
}
```

The resulting image will have a missing spot then.

**Comment by BolverBlitz** [comment]
A big thank you, it works perfect now in my fork.
