### ISSUE TITLE
Not all users have an avatar

### ISSUE THREAD

**Issue by palant** [duiker101/twitter-interaction-circles#3]
This is a duplicate of #2 which has been closed without being resolved for some reason. I wasted some time on this as well, ideally it would be addressed in this repository.

In my case, the culprit was https://twitter.com/Canpuna - suspended account, no avatar. For some reason, `loadImage(undefined)` results in the process being terminated - no error message, nothing indicating what happened. `image.js` should really check whether `users[i].avatar` is set.

**Comment by duiker101** [comment]
I don't have a user with this problem at hand but https://github.com/duiker101/twitter-interaction-circles/commit/f62b707ea1a8f808e14d89b60c7a71cb9a4a45a0 should fix it, I'll close once confirmed

**Comment by palant** [comment]
Confirmed, I now have the default avatar displayed for this user.

**Comment by BolverBlitz** [comment]
I´m sorry i closed it so early. The first reply in #2 was a working solution and i thought @duiker101 will see it anyway.
